export type Status = "connected" | "idle" | "recording" | "replaying" | "failed";
export type RunnerStatus =
  | "draft"
  | "validated"
  | "approved"
  | "published"
  | "deprecated"
  | "failed";
export type RiskLevel = "low" | "medium" | "high";

export const sessions = [
  {
    id: "s1",
    name: "Local Windows CRM",
    platform: "Windows",
    status: "connected" as Status,
    activeApp: "Salesforce Desktop",
    adapters: ["Windows UI Automation", "Vision Fallback"],
    permissions: "All granted",
    lastActivity: "2 min ago",
  },
  {
    id: "s2",
    name: "macOS Finance App",
    platform: "macOS",
    status: "idle" as Status,
    activeApp: "Numbers",
    adapters: ["macOS Accessibility", "OCR"],
    permissions: "Screen recording pending",
    lastActivity: "12 min ago",
  },
  {
    id: "s3",
    name: "AWS WorkSpaces Patch Test",
    platform: "AWS WorkSpaces",
    status: "replaying" as Status,
    activeApp: "Internal Patch Console",
    adapters: ["Vision Fallback", "Keyboard/Mouse"],
    permissions: "All granted",
    lastActivity: "just now",
  },
];

export const extensions = [
  {
    id: "e1",
    name: "Playwright Web Adapter",
    category: "Web & Browser",
    description: "Automate any modern web app via Playwright with DOM-level reliability.",
    installed: true,
    capabilities: ["DOM", "Network", "Screenshots"],
    platforms: ["All"],
    permissions: ["Network access"],
    runtime: "sidecar",
  },
  {
    id: "e2",
    name: "Browser DOM Adapter",
    category: "Web & Browser",
    description: "Attach to existing browser sessions and read live DOM trees.",
    installed: true,
    capabilities: ["DOM", "Selectors"],
    platforms: ["All"],
    permissions: ["Browser bridge"],
    runtime: "sidecar",
  },
  {
    id: "e3",
    name: "Windows UI Automation Adapter",
    category: "Native Desktop",
    description: "Drive native Windows apps using UIA control trees.",
    installed: true,
    capabilities: ["UI Tree", "Inputs", "Window Mgmt"],
    platforms: ["Windows"],
    permissions: ["Accessibility"],
    runtime: "native",
  },
  {
    id: "e4",
    name: "macOS Accessibility Adapter",
    category: "Native Desktop",
    description: "Use AX APIs to inspect and control macOS apps.",
    installed: true,
    capabilities: ["AX Tree", "Inputs"],
    platforms: ["macOS"],
    permissions: ["Accessibility", "Screen recording"],
    runtime: "native",
  },
  {
    id: "e5",
    name: "Linux X11 Adapter",
    category: "Native Desktop",
    description: "AT-SPI and X11 automation for traditional Linux desktops.",
    installed: true,
    capabilities: ["AT-SPI", "X11"],
    platforms: ["Linux X11"],
    permissions: ["AT-SPI"],
    runtime: "native",
  },
  {
    id: "e6",
    name: "Linux Wayland Compatibility Adapter",
    category: "Native Desktop",
    description: "Compatibility shim for Wayland desktops via portals.",
    installed: false,
    capabilities: ["Portals"],
    platforms: ["Linux Wayland"],
    permissions: ["Screen capture portal"],
    runtime: "native",
  },
  {
    id: "e7",
    name: "Java Desktop Adapter",
    category: "Legacy & Enterprise",
    description: "Automate Swing, AWT and JavaFX desktop applications.",
    installed: true,
    capabilities: ["JFC Tree", "Inputs"],
    platforms: ["All"],
    permissions: ["Java agent"],
    runtime: "sidecar",
    update: true,
  },
  {
    id: "e8",
    name: "Terminal Adapter",
    category: "Legacy & Enterprise",
    description: "Drive shell-based workflows with deterministic prompts.",
    installed: false,
    capabilities: ["PTY", "Stream"],
    platforms: ["All"],
    permissions: ["Shell"],
    runtime: "sidecar",
  },
  {
    id: "e9",
    name: "TN3270 Mainframe Adapter",
    category: "Legacy & Enterprise",
    description: "Connect to IBM 3270 mainframe sessions.",
    installed: false,
    capabilities: ["3270 Screens"],
    platforms: ["All"],
    permissions: ["Network"],
    runtime: "sidecar",
  },
  {
    id: "e10",
    name: "Citrix / Remote Desktop Vision Adapter",
    category: "Legacy & Enterprise",
    description: "Vision-driven automation for Citrix and RDP sessions.",
    installed: false,
    capabilities: ["Vision", "OCR"],
    platforms: ["Citrix", "RDP"],
    permissions: ["Screen capture"],
    runtime: "sidecar",
  },
  {
    id: "e11",
    name: "Vision & Screenshot Adapter",
    category: "Fallbacks",
    description: "Visual fallback for any app the structured adapters can't reach.",
    installed: true,
    capabilities: ["Vision", "Templates"],
    platforms: ["All"],
    permissions: ["Screen capture"],
    runtime: "native",
  },
  {
    id: "e12",
    name: "OCR Adapter",
    category: "Fallbacks",
    description: "Extract text from any region of any screen.",
    installed: false,
    capabilities: ["OCR"],
    platforms: ["All"],
    permissions: ["Screen capture"],
    runtime: "sidecar",
  },
  {
    id: "e13",
    name: "Keyboard/Mouse Fallback Adapter",
    category: "Fallbacks",
    description: "Low-level input emulation when nothing else works.",
    installed: true,
    capabilities: ["Inputs"],
    platforms: ["All"],
    permissions: ["Input control"],
    runtime: "native",
  },
];

export const runners = [
  {
    id: "r1",
    name: "crm.create_customer",
    description: "Create a new customer in the CRM and return the customer ID.",
    version: "1.4.0",
    status: "published" as RunnerStatus,
    risk: "medium" as RiskLevel,
    adapters: ["Windows UI Automation"],
    lastTest: "passed",
    updated: "2h ago",
    owner: "Avery K.",
  },
  {
    id: "r2",
    name: "billing.create_account",
    description: "Create a billing account after CRM onboarding.",
    version: "0.9.2",
    status: "approved" as RunnerStatus,
    risk: "high" as RiskLevel,
    adapters: ["Playwright Web"],
    lastTest: "passed",
    updated: "yesterday",
    owner: "Priya S.",
  },
  {
    id: "r3",
    name: "supplier.download_invoice",
    description: "Download all unpaid invoices from supplier portal.",
    version: "2.1.0",
    status: "published" as RunnerStatus,
    risk: "low" as RiskLevel,
    adapters: ["Playwright Web"],
    lastTest: "passed",
    updated: "3d ago",
    owner: "Diego R.",
  },
  {
    id: "r4",
    name: "workspace.validate_patch",
    description: "Validate a patch in AWS WorkSpaces and capture evidence.",
    version: "0.3.0",
    status: "validated" as RunnerStatus,
    risk: "high" as RiskLevel,
    adapters: ["Vision Fallback"],
    lastTest: "failed",
    updated: "5h ago",
    owner: "Sam L.",
  },
  {
    id: "r5",
    name: "mainframe.lookup_customer",
    description: "Look up a customer record in legacy TN3270 mainframe.",
    version: "1.0.0",
    status: "draft" as RunnerStatus,
    risk: "medium" as RiskLevel,
    adapters: ["TN3270"],
    lastTest: "—",
    updated: "10m ago",
    owner: "Jordan M.",
  },
];

export const mcpTools = [
  {
    id: "m1",
    name: "crm_create_customer",
    runner: "crm.create_customer",
    description: "Creates a customer record in the connected CRM.",
    status: "enabled",
    version: "1.4.0",
    successRate: 98.4,
    lastCall: "1 min ago",
  },
  {
    id: "m2",
    name: "billing_create_account",
    runner: "billing.create_account",
    description: "Provisions a new billing account.",
    status: "enabled",
    version: "0.9.2",
    successRate: 96.1,
    lastCall: "12 min ago",
  },
  {
    id: "m3",
    name: "supplier_download_invoice",
    runner: "supplier.download_invoice",
    description: "Downloads unpaid invoices from supplier portal.",
    status: "enabled",
    version: "2.1.0",
    successRate: 99.7,
    lastCall: "4 min ago",
  },
  {
    id: "m4",
    name: "workspace_validate_patch",
    runner: "workspace.validate_patch",
    description: "Validates a patch in AWS WorkSpaces.",
    status: "failing",
    version: "0.3.0",
    successRate: 71.2,
    lastCall: "30 min ago",
  },
];

export const recordings = [
  {
    id: "rec1",
    name: "Create CRM customer (manual)",
    app: "Salesforce Desktop",
    session: "Local Windows CRM",
    duration: "1:42",
    events: 38,
    status: "Draft Created",
    created: "2h ago",
  },
  {
    id: "rec2",
    name: "Download supplier invoice",
    app: "Supplier Portal",
    session: "Local Windows CRM",
    duration: "0:58",
    events: 22,
    status: "Normalising",
    created: "5h ago",
  },
  {
    id: "rec3",
    name: "Mainframe customer lookup",
    app: "TN3270",
    session: "AWS WorkSpaces",
    duration: "0:34",
    events: 14,
    status: "Draft Created",
    created: "yesterday",
  },
];

export const approvals = [
  {
    id: "a1",
    runner: "billing.create_account",
    action: "Publish v0.9.2 as MCP tool",
    risk: "high" as RiskLevel,
    requestedBy: "Priya S.",
    evidence: "12 screenshots, 3 assertions passed",
  },
  {
    id: "a2",
    runner: "workspace.validate_patch",
    action: "Approve high-risk replay",
    risk: "high" as RiskLevel,
    requestedBy: "Sam L.",
    evidence: "Failed assertion on step 7",
  },
];

export const activity = [
  { id: 1, time: "2m", text: "crm.create_customer v1.4.0 published as MCP tool", kind: "success" },
  { id: 2, time: "14m", text: "Recording 'Create CRM customer (manual)' normalised", kind: "info" },
  { id: 3, time: "1h", text: "workspace.validate_patch test failed on step 7", kind: "error" },
  { id: 4, time: "3h", text: "Java Desktop Adapter has an update available", kind: "warning" },
  {
    id: 5,
    time: "yesterday",
    text: "billing.create_account approved by Avery K.",
    kind: "success",
  },
];
