/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunnersRouteImport } from './routes/runners'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunnersRunnerIdEditRouteImport } from './routes/runners.$runnerId.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnersRoute = RunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnersRunnerIdEditRoute = RunnersRunnerIdEditRouteImport.update({
  id: '/$runnerId/edit',
  path: '/$runnerId/edit',
  getParentRoute: () => RunnersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/mcp': typeof McpRoute
  '/runners': typeof RunnersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/runners/$runnerId/edit': typeof RunnersRunnerIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/mcp': typeof McpRoute
  '/runners': typeof RunnersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/runners/$runnerId/edit': typeof RunnersRunnerIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/mcp': typeof McpRoute
  '/runners': typeof RunnersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/runners/$runnerId/edit': typeof RunnersRunnerIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/mcp'
    | '/runners'
    | '/settings'
    | '/runners/$runnerId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/mcp'
    | '/runners'
    | '/settings'
    | '/runners/$runnerId/edit'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/mcp'
    | '/runners'
    | '/settings'
    | '/runners/$runnerId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  McpRoute: typeof McpRoute
  RunnersRoute: typeof RunnersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runners': {
      id: '/runners'
      path: '/runners'
      fullPath: '/runners'
      preLoaderRoute: typeof RunnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runners/$runnerId/edit': {
      id: '/runners/$runnerId/edit'
      path: '/$runnerId/edit'
      fullPath: '/runners/$runnerId/edit'
      preLoaderRoute: typeof RunnersRunnerIdEditRouteImport
      parentRoute: typeof RunnersRoute
    }
  }
}

interface RunnersRouteChildren {
  RunnersRunnerIdEditRoute: typeof RunnersRunnerIdEditRoute
}

const RunnersRouteChildren: RunnersRouteChildren = {
  RunnersRunnerIdEditRoute: RunnersRunnerIdEditRoute,
}

const RunnersRouteWithChildren =
  RunnersRoute._addFileChildren(RunnersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  McpRoute: McpRoute,
  RunnersRoute: RunnersRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
