name: Reusable Rust

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  rust:
    runs-on: ubuntu-latest
    env:
      CARGO_HTTP_MULTIPLEXING: "false"
      CARGO_HTTP_TIMEOUT: "120"
      CARGO_NET_RETRY: "10"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run command
        shell: bash
        run: ${{ inputs.command }}
